List ShoppingList=[
  {
    'name':'Ajio',
    'image':'assets/ajio.png',
    'url':'https://www.ajio.com/',
  },
  {
    'name':'Amazon',
    'image':'assets/amazon.jpg',
    'url':'https://www.amazon.in/',
  },
  {
    'name':'Myntra',
    'image':'assets/myntra.jpg',
    'url':'https://www.myntra.com/',
  },
  {
    'name':'Meesho',
    'image':'assets/meesho.jpg',
    'url':'https://www.meesho.com/',
  },
  {
    'name':'Flipkart',
    'image':'assets/flipcart.png',
    'url':'https://www.flipkart.com/',
  },
  {
    'name':'Snapdeal',
    'image':'assets/snapdeal.png',
    'url':'https://www.snapdeal.com/',
  },

];